 kNN -> vizinhos mais próximos

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Carregando a base localmente ou usando a própria base do python, conforme a seguir:
-from sklearn.datasets import load_iris
-iris = load_iris()
-type(iris)

1 Carregar o base iris usando sklearn.datasets
2 Separar os dados em treino e teste usando train_test_split
3 Treinar o k-NN e avaliar o modelo

In [2]:
# carregando a base internamente
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils._bunch.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [6]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

Associando classes aos exemplos

Vamos trabalhar com o NumPy para indexar um vetor por:

-índices
-fatiamento
-máscara
-vetor de índices

In [8]:
gerador = np.random.RandomState(1337)
vetor = gerador.randint(1, 7, 10)
vetor

array([6, 5, 1, 2, 3, 3, 3, 5, 1, 2], dtype=int32)

Acesso ao vetor por índice:

In [9]:
vetor[0]

np.int32(6)

In [10]:
vetor[-1]

np.int32(2)

Acesso por fatiamento

In [11]:
vetor[3:6]

array([2, 3, 3], dtype=int32)

In [12]:
vetor[:5]

array([6, 5, 1, 2, 3], dtype=int32)

In [13]:
vetor[2:8:2]

array([1, 3, 3], dtype=int32)

Acesso por máscara

In [14]:
vetor %2 == 0

array([ True, False, False,  True, False, False, False, False, False,
        True])

In [15]:
vetor[vetor %2 == 0]

array([6, 2, 2], dtype=int32)

In [16]:
m = vetor %2 == 0
m

array([ True, False, False,  True, False, False, False, False, False,
        True])

In [17]:
vetor[m]

array([6, 2, 2], dtype=int32)

In [18]:
~m

array([False,  True,  True, False,  True,  True,  True,  True,  True,
       False])

In [19]:
vetor[~m]

array([5, 1, 3, 3, 3, 5, 1], dtype=int32)

Acesso por fancy indexing

In [20]:
vetor[[0, 2, 1, 3]]

array([6, 1, 5, 2], dtype=int32)

In [21]:
vetor[[[0,1],[2,3]]]

array([[6, 5],
       [1, 2]], dtype=int32)

Usando fancy indexing no vetor de rótulos

In [22]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [24]:
iris.target_names[iris.target]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

Separando conjuntos de treino, teste e validação

- treino: para encontrar os parâmetros/treinar o modelo
- teste: para prever o desempenho do modelo
- validação: para testar e ajustar hiperparâmetro

In [25]:
from sklearn.model_selection import train_test_split

Ilustrando para aprendizado não supervisionado:

In [26]:
matriz = np.arange(1, 11).reshape(-1,1)
matriz

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [27]:
m_treino, m_teste = train_test_split(matriz)
m_treino

array([[ 9],
       [10],
       [ 8],
       [ 6],
       [ 2],
       [ 4],
       [ 3]])

In [28]:
m_teste

array([[1],
       [7],
       [5]])

Gerando conjunto de teste para a base iris

Separação da base Iris em 30% para teste.

In [29]:
X_treino_e_validacao, X_teste, y_treino_e_validacao, y_teste = train_test_split(
    iris.data, iris.target, test_size=0.3, random_state=42
)

Contagem de elementos por classe. Perfeitamente balanceados no conjunto original.

In [30]:
for classe in range(3):
    num = sum(iris.target == classe)
    pct = 100 * num / len(iris.target)
    print(f'Numero de exemplos de classe {classe} no conjunto original : {num} ({pct:.2f}%)')

Numero de exemplos de classe 0 no conjunto original : 50 (33.33%)
Numero de exemplos de classe 1 no conjunto original : 50 (33.33%)
Numero de exemplos de classe 2 no conjunto original : 50 (33.33%)


Agora para o nosso conjunto de teste...

In [31]:
for classe in range(3):
    num = sum(y_teste == classe)
    pct = 100 * num / len(y_teste)
    print(f'Numero de exemplos de classe {classe} no conjunto de teste : {num} ({pct:.2f}%)')

Numero de exemplos de classe 0 no conjunto de teste : 19 (42.22%)
Numero de exemplos de classe 1 no conjunto de teste : 13 (28.89%)
Numero de exemplos de classe 2 no conjunto de teste : 13 (28.89%)


Separando novamente com estratificação.

In [32]:
X_treino_e_validacao, X_teste, y_treino_e_validacao, y_teste = train_test_split(
    iris.data, iris.target, test_size=0.3, random_state=42, stratify=iris.target
)

In [33]:
for classe in range(3):
    num = sum(y_teste == classe)
    pct = 100 * num / len(y_teste)
    print(f'Numero de exemplos de classe {classe} no conjunto de teste : {num} ({pct:.2f}%)')

Numero de exemplos de classe 0 no conjunto de teste : 15 (33.33%)
Numero de exemplos de classe 1 no conjunto de teste : 15 (33.33%)
Numero de exemplos de classe 2 no conjunto de teste : 15 (33.33%)


Gerando conjunto de treino e de validação

Mostrando o conjunto de treino e validação:

In [34]:
X_treino_e_validacao.shape

(105, 4)

Separando em treino e validação

In [46]:
X_treino, X_val, y_treino, y_val = train_test_split(
    X_treino_e_validacao, y_treino_e_validacao, test_size=0.2,
    stratify=y_treino_e_validacao, random_state=123
)

In [47]:
X_treino.shape

(84, 4)

In [48]:
X_val.shape

(21, 4)

In [49]:
X_teste.shape

(45, 4)

In [50]:
for classe in range(3):
    num = sum(y_val == classe)
    pct = 100 * num / len(y_val)
    print(f'Numemro de exemplos da classe {classe} no conjunto de validação: {num} ({pct:.2f}%)')

Numemro de exemplos da classe 0 no conjunto de validação: 7 (33.33%)
Numemro de exemplos da classe 1 no conjunto de validação: 7 (33.33%)
Numemro de exemplos da classe 2 no conjunto de validação: 7 (33.33%)


Treinar e valida o k-NN com diferentes valores de k

In [51]:
# importando o modelo KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [52]:
# instanciando e treinando o modelo
h1 = KNeighborsClassifier(n_neighbors=1)
h1.fit(X_treino, y_treino)

KNeighborsClassifier(n_neighbors=1)

In [53]:
# definindo a predição
ypred = h1.predict(X_val)

In [54]:
# encontrando o valor da acurácia
accuracy_score(y_val, ypred)

0.8571428571428571

In [56]:
for k in [1, 3, 5, 6, 8, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80]:
    h = KNeighborsClassifier(n_neighbors=k)
    h.fit(X_treino, y_treino);
    ypred = h.predict(X_val)
    print(f'k = {k}, Acurácia = {100*accuracy_score(y_val, ypred):.2f}%')

k = 1, Acurácia = 85.71%
k = 3, Acurácia = 90.48%
k = 5, Acurácia = 90.48%
k = 6, Acurácia = 95.24%
k = 8, Acurácia = 95.24%
k = 10, Acurácia = 95.24%
k = 15, Acurácia = 90.48%
k = 20, Acurácia = 90.48%
k = 25, Acurácia = 85.71%
k = 30, Acurácia = 90.48%
k = 40, Acurácia = 90.48%
k = 50, Acurácia = 90.48%
k = 60, Acurácia = 66.67%
k = 70, Acurácia = 66.67%
k = 80, Acurácia = 57.14%


Teste final: agora vamos testar todos os dados de treino no conjunto de teste

In [57]:
X_treino = X_treino_e_validacao
y_treino = y_treino_e_validacao

Treinar k=6 nesse conjunto e testar em (Xteste, yteste) --> continuar

=========================================================================================================================